// Image paths use /gallery/ which maps to the public/ folder in the frontend build.
// These paths are stable across Vite builds and Vercel deployment.
export const initialProducts = [
  {
    productId: "prod-1",
    name: "Royal Zardosi Silk Blouse",
    category: "Blouses",
    price: 699,
    originalPrice: 900,
    rating: 4.9,
    reviewCount: 28,
    image: "/gallery/blouse-1.jpeg",
    images: ["/gallery/blouse-1.jpeg", "/gallery/blouse-2.jpeg", "/gallery/blouse-3.jpeg"],
    description: "Handcrafted pure silk blouse featuring intricate Zardosi embroidery around the neckline and sleeves. Stitched with comfortable padded cups and soft inner lining.",
    availableSizes: ["32 (S)", "34 (M)", "36 (L)", "38 (XL)", "Custom Measurement"],
    inStock: true,
    featured: true,
  },
  {
    productId: "prod-2",
    name: "Velvet Bridal Heavy Blouse",
    category: "Blouses",
    price: 949,
    originalPrice: 1200,
    rating: 5.0,
    reviewCount: 35,
    image: "/gallery/blouse-2.jpeg",
    images: ["/gallery/blouse-2.jpeg", "/gallery/blouse-1.jpeg", "/gallery/blouse-3.jpeg"],
    description: "Luxury micro-velvet bridal blouse decorated with gold thread embroidery and stone accents. Perfect for grand wedding functions and festive sarees.",
    availableSizes: ["32 (S)", "34 (M)", "36 (L)", "38 (XL)", "Custom Measurement"],
    inStock: true,
    featured: true,
  },
  {
    productId: "prod-3",
    name: "Classic Boatneck Cotton Silk Blouse",
    category: "Blouses",
    price: 450,
    originalPrice: 750,
    rating: 4.7,
    reviewCount: 19,
    image: "/gallery/blouse-3.jpeg",
    images: ["/gallery/blouse-3.jpeg", "/gallery/blouse-1.jpeg"],
    description: "Elegant boatneck blouse crafted in breathable cotton silk fabric. Ideal for everyday office wear as well as semi-formal family gatherings.",
    availableSizes: ["32 (S)", "34 (M)", "36 (L)", "38 (XL)", "Custom Measurement"],
    inStock: true,
    featured: false,
  },
  {
    productId: "prod-4",
    name: "Pastel Florals Designer Lehenga Choli",
    category: "Lehengas",
    price: 2559,
    originalPrice: 4500,
    rating: 4.9,
    reviewCount: 42,
    image: "/gallery/lehenga-1.jpeg",
    images: ["/gallery/lehenga-1.jpeg", "/gallery/lehenga-2.jpeg", "/gallery/lehenga-3.jpeg"],
    description: "Breathtaking pastel pink organza lehenga choli with delicate floral thread embroidery, voluminous flared ghera, and matching net dupatta.",
    availableSizes: ["S", "M", "L", "XL", "Custom Measurement"],
    inStock: true,
    featured: true,
  },
  {
    productId: "prod-5",
    name: "Crimson Red Velvet Bridal Lehenga Set",
    category: "Lehengas",
    price: 6999,
    originalPrice: 8000,
    rating: 5.0,
    reviewCount: 56,
    image: "/gallery/lehenga-2.jpeg",
    images: ["/gallery/lehenga-2.jpeg", "/gallery/lehenga-1.jpeg", "/gallery/lehenga-3.jpeg"],
    description: "Royal crimson red velvet lehenga set with traditional bridal dori and gota patti craftsmanship. Designed for brides who appreciate timeless elegance.",
    availableSizes: ["S", "M", "L", "XL", "Custom Measurement"],
    inStock: true,
    featured: true,
  },
  {
    productId: "prod-6",
    name: "Georgette Festive Flared Lehenga",
    category: "Lehengas",
    price: 5499,
    originalPrice: 7999,
    rating: 4.8,
    reviewCount: 22,
    image: "/gallery/lehenga-3.jpeg",
    images: ["/gallery/lehenga-3.jpeg", "/gallery/lehenga-1.jpeg"],
    description: "Lightweight georgette lehenga featuring mirror work highlights and a stylish tie-back blouse. Comfortable for sangeet and garba dance events.",
    availableSizes: ["S", "M", "L", "XL", "Custom Measurement"],
    inStock: true,
    featured: false,
  },
  {
    productId: "prod-7",
    name: "Embroidered Silk Anarkali Dress",
    category: "Dresses",
    price: 2999,
    originalPrice: 3999,
    rating: 4.8,
    reviewCount: 31,
    image: "/gallery/dress-1.jpg",
    images: ["/gallery/dress-1.jpg", "/gallery/dress-2.jpeg", "/gallery/dress-3.jpeg"],
    description: "Floor-length silk Anarkali gown adorned with delicate zari embroidery along the yoke and sleeve cuffs. Includes pants and organza dupatta.",
    availableSizes: ["S", "M", "L", "XL", "Custom Measurement"],
    inStock: true,
    featured: true,
  },
  {
    productId: "prod-8",
    name: "Indo-Western Peplum & Sharara Suit",
    category: "Dresses",
    price: 1599,
    originalPrice: 2000,
    rating: 4.9,
    reviewCount: 17,
    image: "/gallery/dress-2.jpeg",
    images: ["/gallery/dress-2.jpeg", "/gallery/dress-1.jpg"],
    description: "Modern peplum style short kurti paired with multi-tiered flared sharara pants. Stylish outfit for festive family dinners.",
    availableSizes: ["S", "M", "L", "XL", "Custom Measurement"],
    inStock: true,
    featured: false,
  },
  {
    productId: "prod-9",
    name: "Contemporary Layered Indo-Western Gown",
    category: "Dresses",
    price: 1799,
    originalPrice: 3499,
    rating: 4.9,
    reviewCount: 24,
    image: "/gallery/dress-3.jpeg",
    images: ["/gallery/dress-3.jpeg", "/gallery/dress-1.jpg"],
    description: "Fluid layered chiffon gown with a structured embroidered belt and cap sleeves. Subtle luxury designed for receptions.",
    availableSizes: ["S", "M", "L", "XL", "Custom Measurement"],
    inStock: true,
    featured: false,
  },
  {
    productId: "prod-10",
    name: "Handcrafted Chanderi Kurti Set",
    category: "Other",
    price: 2199,
    originalPrice: 2799,
    rating: 4.7,
    reviewCount: 15,
    image: "/gallery/other-1.jpeg",
    images: ["/gallery/other-1.jpeg", "/gallery/other-2.jpeg"],
    description: "Straight-cut Chanderi kurti with intricate neck embroidery, paired with cotton pants and printed dupatta.",
    availableSizes: ["S", "M", "L", "XL", "Custom Measurement"],
    inStock: true,
    featured: false,
  },
  {
    productId: "prod-11",
    name: "Designer Festive Kurta & Pants",
    category: "Other",
    price: 2399,
    originalPrice: 3499,
    rating: 4.8,
    reviewCount: 18,
    image: "/gallery/other-2.jpeg",
    images: ["/gallery/other-2.jpeg", "/gallery/other-3.jpeg"],
    description: "A-line festive kurta set with delicate pearl lace detailing along the neck and sleeve borders.",
    availableSizes: ["S", "M", "L", "XL", "Custom Measurement"],
    inStock: true,
    featured: false,
  },
  {
    productId: "prod-12",
    name: "Custom Tailored Angrakha Kurti",
    category: "Other",
    price: 1999,
    originalPrice: 2999,
    rating: 4.9,
    reviewCount: 21,
    image: "/gallery/other-3.jpeg",
    images: ["/gallery/other-3.jpeg", "/gallery/other-1.jpeg"],
    description: "Traditional overlap Angrakha kurti tied with handmade pom-pom tassels. Customized to your bust and armhole measurements.",
    availableSizes: ["S", "M", "L", "XL", "Custom Measurement"],
    inStock: true,
    featured: false,
  },
];
